global using System.Globalization;
global using FluentValidation;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Forms;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Options;
global using MudBlazor;
global using Vioren.CodebaseAtom.WebUI.Common.Statics;
global using Vioren.CodebaseAtom.WebUI.Common.Validators;
global using Vioren.CodebaseAtom.WebUI.Components.Extensions;
global using Vioren.CodebaseAtom.WebUI.Domain.Common.Abstracts;
global using Vioren.CodebaseAtom.WebUI.Domain.Common.Statics;
global using Vioren.CodebaseAtom.WebUI.Domain.Entities;
global using Vioren.CodebaseAtom.WebUI.Domain.Enums;
global using Vioren.CodebaseAtom.WebUI.Domain.Statics;
global using Vioren.CodebaseAtom.WebUI.Infrastructure.CurrentUser;
global using Vioren.CodebaseAtom.WebUI.Infrastructure.Database;
global using Vioren.CodebaseAtom.WebUI.Infrastructure.Identity.Statics;
global using Vioren.CodebaseAtom.WebUI.Infrastructure.Options;
global using Vioren.CodebaseAtom.WebUI.Logics.Common.Exceptions;
global using Vioren.CodebaseAtom.WebUI.Logics.Common.Extensions;
global using Vioren.CodebaseAtom.WebUI.Logics.Common.Statics;
global using AccountProfileRouteFor = Vioren.CodebaseAtom.WebUI.Components.Features.Account.Pages.Profile.Statics.RouteFor;
global using AccountRouteFor = Vioren.CodebaseAtom.WebUI.Components.Features.Account.Statics.RouteFor;
global using CalculatorRouteFor = Vioren.CodebaseAtom.WebUI.Components.Features.Calculator.Statics.RouteFor;
global using ComponentsBreadcrumbFor = Vioren.CodebaseAtom.WebUI.Components.Statics.BreadcrumbFor;
global using ExamplesBreadcrumbFor = Vioren.CodebaseAtom.WebUI.Components.Features.Examples.Statics.BreadcrumbFor;
global using ExamplesDisplayTextFor = Vioren.CodebaseAtom.WebUI.Components.Features.Examples.Statics.DisplayTextFor;
global using ExamplesRouteFor = Vioren.CodebaseAtom.WebUI.Components.Features.Examples.Statics.RouteFor;
global using HomeBreadcrumbFor = Vioren.CodebaseAtom.WebUI.Components.Features.Home.Statics.BreadcrumbFor;
global using HomeRouteFor = Vioren.CodebaseAtom.WebUI.Components.Features.Home.Statics.RouteFor;
global using ProjectsBreadcrumbFor = Vioren.CodebaseAtom.WebUI.Components.Features.Projects.Statics.BreadcrumbFor;
global using ProjectsRouteFor = Vioren.CodebaseAtom.WebUI.Components.Features.Projects.Statics.RouteFor;
