global using CodebaseAtom.WebUI.Common.Statics;
global using CodebaseAtom.WebUI.Components.Extensions;
global using CodebaseAtom.WebUI.Domain.Common.Abstracts;
global using CodebaseAtom.WebUI.Domain.Common.Statics;
global using CodebaseAtom.WebUI.Domain.Entities;
global using CodebaseAtom.WebUI.Domain.Enums;
global using CodebaseAtom.WebUI.Domain.Statics;
global using CodebaseAtom.WebUI.Infrastructure.Database;
global using CodebaseAtom.WebUI.Infrastructure.Identity.Statics;
global using CodebaseAtom.WebUI.Infrastructure.Options;
global using CodebaseAtom.WebUI.Logics.Common.Exceptions;
global using CodebaseAtom.WebUI.Logics.Common.Extensions;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Forms;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Options;
global using MudBlazor;
global using AccountProfileRouteFor = CodebaseAtom.WebUI.Components.Features.Account.Pages.Profile.Statics.RouteFor;
global using AccountRouteFor = CodebaseAtom.WebUI.Components.Features.Account.Statics.RouteFor;
global using ComponentsBreadcrumbFor = CodebaseAtom.WebUI.Components.Statics.BreadcrumbFor;
global using ExamplesBreadcrumbFor = CodebaseAtom.WebUI.Components.Features.Examples.Statics.BreadcrumbFor;
global using ExamplesDisplayTextFor = CodebaseAtom.WebUI.Components.Features.Examples.Statics.DisplayTextFor;
global using ExamplesRouteFor = CodebaseAtom.WebUI.Components.Features.Examples.Statics.RouteFor;
global using HomeBreadcrumbFor = CodebaseAtom.WebUI.Components.Features.Home.Statics.BreadcrumbFor;
global using HomeRouteFor = CodebaseAtom.WebUI.Components.Features.Home.Statics.RouteFor;
global using ProjectsBreadcrumbFor = CodebaseAtom.WebUI.Components.Features.Projects.Statics.BreadcrumbFor;
global using ProjectsRouteFor = CodebaseAtom.WebUI.Components.Features.Projects.Statics.RouteFor;
